name: Rust
on:
  pull_request:
    paths:
      - .github/workflows/rust.yml
      - Cargo.toml
      - ci/**
      - crates/**
  push:
    branches: main
    paths:
      - .github/workflows/rust.yml
      - Cargo.toml
      - ci/**
      - crates/**

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 1
  CARGO_PROFILE_RELEASE_DEBUG: 1
  RUST_BACKTRACE: short
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  cleanup-runs:
    runs-on: buildjet-16vcpu-ubuntu-2004
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  fmt:
    runs-on: buildjet-16vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  
  doc:
    runs-on: buildjet-16vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features --release

  test-stable:
    runs-on: buildjet-16vcpu-ubuntu-2004
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast --no-run
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast --workspace -- --nocapture
